services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web-app:
    build: .
    user: root
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0 -p 80"
    volumes:
      - .:/rails
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

volumes:
  postgres_data:
